# Generated by Django 3.1.3 on 2020-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='localisations',
            field=models.ManyToManyField(null=True, to='time_app.Localisation'),
        ),
    ]
