# Generated by Django 3.1.3 on 2020-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0002_auto_20201112_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='localisations',
            field=models.ManyToManyField(to='time_app.Localisation'),
        ),
    ]
